#!/bin/bash         
echo "Compiling $PYFILE ..."
python3 -m compileall $PYFILE

# Move the compiled file and append 'c' to its name
mv __pycache__/$(basename $PYFILE .py).cpython-3*.pyc $(basename $PYFILE .py)'c'.pyc

# Remove the __pycache__ directory
rmdir __pycache__
